[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "microbit MicroPython"
authors = [{name = "March Harald", email = "matheharry@outlook.com"}]
dynamic = ["version", "description"]
